console.log('V1 event engine loaded');
function v1eInit(){state.events=state.events||[];state.factionHatred=state.factionHatred||{};state.kinship=state.kinship||{};for(const a of state.actors){if(!state.kinship[a.id])state.kinship[a.id]={master:null,senior:null,sect:a.sect}}saveWorld()}
function v1eEvent(type,text,data={}){state.events.unshift({id:'e'+Date.now()+Math.random().toString(16).slice(2),type,text,data,day:state.day,year:state.year,season:getSeason(state)});state.events=state.events.slice(0,300);addLog(state,text,type)}
function v1eRelatives(a){const all=state.actors.filter(x=>x.id!==a.id&&x.alive);let pool=[];if(a.sect&&a.sect!=='无门派')pool=all.filter(x=>x.sect===a.sect);if(!pool.length)pool=all.filter(x=>x.location===a.location);return pool.slice(0,3)}
function v1eHate(source,target,amount,reason){changeHatred(source.id,target.id,amount);changeRelation(source.id,target.id,-Math.ceil(amount/2));v1eEvent('hate',`${source.name}因为${reason}记恨${target.name}。`,{source:source.id,target:target.id,amount,reason})}
function v1eFactionHate(sect,target,amount,reason){if(!sect||sect==='无门派')return;state.factionHatred[sect]=(state.factionHatred[sect]||0)+amount;v1eEvent('faction',`${sect}因${reason}对${target.name}的敌意上升到 ${state.factionHatred[sect]}。`,{sect,target:target.id,amount});if(state.factionHatred[sect]>=80)v1eEvent('wanted',`${sect}开始在各地通缉${target.name}。`,{sect,target:target.id})}
function v1eAttack(targetId){v1eInit();const p=findActor('player'),t=findActor(targetId);if(!p||!t||!t.alive)return;const hit=randInt(8,28)+p.realm*5;const back=randInt(3,18)+t.realm*4;t.hp=clamp(t.hp-hit,0,t.maxHp);p.hp=clamp(p.hp-back,0,p.maxHp);v1eEvent('fight',`${p.name}与${t.name}发生冲突，${t.name}受伤 ${hit}，你受伤 ${back}。`,{target:t.id});v1eHate(t,p,35,'被你攻击');for(const r of v1eRelatives(t))v1eHate(r,p,18,`${t.name}被你攻击`);v1eFactionHate(t.sect,p,20,`${t.name}被攻击`);if(t.hp<=0){killActor(t,`${p.name}攻击`);v1eEvent('death',`${t.name}死在你手中。`,{target:t.id});for(const r of v1eRelatives(t))v1eHate(r,p,45,`${t.name}被你杀死`);v1eFactionHate(t.sect,p,55,`${t.name}被杀`)}saveWorld();render()}
function v1eRandomWorld(){v1eInit();const p=findActor('player');if(!p||!p.alive)return;if(roll(25)){const same=state.actors.filter(a=>a.alive&&!a.isPlayer&&a.location===p.location);if(same.length){const n=pick(same);v1eEvent('local',`${n.name}在${getLocationName(p.location)}出现，似乎有自己的打算。`,{npc:n.id})}}
for(const a of state.actors.filter(x=>x.alive&&!x.isPlayer)){const h=getHatred(state,a.id,'player');if(h>30&&roll(Math.min(60,h))){a.location=p.location;v1eEvent('revenge',`${a.name}循着消息来到${getLocationName(p.location)}，似乎是来找你的。`,{npc:a.id});break}}
for(const [sect,h] of Object.entries(state.factionHatred||{})){if(h>80&&roll(18)){const hunter=state.actors.find(a=>a.alive&&!a.isPlayer&&a.sect===sect)||state.actors.find(a=>a.alive&&!a.isPlayer);if(hunter){hunter.location=p.location;v1eEvent('wanted',`${sect}的追查波及${getLocationName(p.location)}，${hunter.name}出现在附近。`,{sect,npc:hunter.id})}}}}
const v1eOldAdvance=advanceOneDay;advanceOneDay=function(){v1eOldAdvance();v1eRandomWorld()}
const v1eOldScene=renderScene;renderScene=function(){v1eInit();const p=findActor('player');const loc=getLocation(p.location);const near=state.actors.filter(a=>a.alive&&a.location===p.location&&a.id!==p.id).slice(0,8);const exits=LOCATIONS.filter(x=>x.id!==p.location).slice(0,6);el.scenePanel.innerHTML=`<div class="v1-scene-wrap"><div class="v1-scene-text"><div class="scene-title">${getLocationName(p.location)}</div><p>${loc.desc} 这里没有固定任务。世界会因为你和每个人的接触、冲突、救助、伤害而改变。</p><div class="scene-block"><h3>身边人物</h3><div class="v1-nearby">${near.map(a=>`<span>${a.name}｜${a.sect}｜仇恨 ${getHatred(state,a.id,'player')}</span><button onclick="v1xTalk('${a.id}')">交谈</button><button onclick="v1eAttack('${a.id}')">冲突</button>`).join('')||'<span>附近暂无人物</span>'}</div></div><div class="scene-block"><h3>可前往地点</h3><div class="v1-nearby">${exits.map(l=>`<button onclick="v1xMoveTo('${l.id}')">${l.name}</button>`).join('')}</div></div><div class="scene-block"><h3>世界因果</h3><p>${Object.entries(state.factionHatred||{}).map(([s,h])=>`${s}敌意 ${h}`).join('｜')||'暂未产生门派级仇恨。'}</p></div></div><div class="v1-scene-art"><b>${getLocationName(p.location)}</b></div></div>`}
v1eInit();render();