console.log('V1 UI loaded');
const V1_FACES=['清秀','俊朗','英武','冷峻','温润','疏朗'];
const V1_BODY=['瘦削','匀称','健壮','修长','魁梧'];
const V1_AURA=['平和','沉稳','冷淡','洒脱','谨慎'];
const V1_ROOT=['杂灵根','三灵根','双灵根','单灵根','天灵根'];
function v1Pick(a){return a[Math.floor(Math.random()*a.length)]}
function v1Profile(a){if(!a)return;a.gender=a.gender||v1Pick(['男','女']);a.face=a.face||v1Pick(V1_FACES);a.body=a.body||v1Pick(V1_BODY);a.aura=a.aura||v1Pick(V1_AURA);a.root=a.root||v1Pick(V1_ROOT);a.charm=a.charm||randInt(35,90);a.bone=a.bone||randInt(35,90);a.wisdom=a.wisdom||randInt(35,90)}
function v1PatchWorld(){state.actors.forEach(v1Profile);const p=findActor('player');if(p&&!state.v1FullInit){p.realm=0;p.exp=0;p.qi=47;p.maxQi=100;p.lifespan=82;p.wealth=44;p.sect='无门派';p.location='starter_village';p.origin='新手村';state.v1FullInit=true;addLog(state,'你从昏迷中醒来，发现自己只是凡人。','system');addLog(state,'村长站在门外，看起来正在等你。','system');addLog(state,'远处的坊市传来车马声。','system');saveWorld()}}
renderWorld=function(){v1PatchWorld();const alive=state.actors.filter(a=>a.alive).length;const dead=state.actors.length-alive;const p=findActor('player');el.worldDate.textContent=`第 ${state.year} 年 ${getSeason(state)} 第 ${state.day} 日`;el.worldSub.textContent=`存活 ${alive} 人｜死亡 ${dead} 人｜门派：${p.sect}｜灵石：${p.wealth}｜修为：${REALM_NAMES[p.realm]}｜气血：${p.hp}/${p.maxHp}｜灵气：${p.qi}/${p.maxQi}`}
renderLogs=function(){const logs=state.logs.slice(0,6);el.logList.innerHTML=logs.map(l=>`<div class="log-item"><strong>${getSeason(state)}日 ${l.day}</strong> ${escapeHtml(l.text)}</div>`).join('')}
renderScene=function(){const p=findActor('player');const loc=getLocation(p.location);const near=state.actors.filter(a=>a.alive&&a.location===p.location&&a.id!==p.id).slice(0,6);el.scenePanel.innerHTML=`<div class="scene-title">${getLocationName(p.location)}</div><p>${loc.desc} 你现在仍是凡人，经脉尚未完全打开。先赚钱维持生计，再尝试修炼感气。</p><div class="scene-block"><h3>当前任务</h3><div class="tutorial-list"><div class="tutorial-item">获得 10 灵石</div><div class="tutorial-item">完成一次修炼，尝试感气</div><div class="tutorial-item">前往坊市，认识一名 NPC</div><div class="tutorial-item">寻找加入门派的机会</div></div></div><div class="scene-block"><h3>附近人物</h3><div>${near.length?near.map(a=>`<span class="badge">${a.name}｜${a.gender}｜${a.face}</span>`).join(' '):'<span class="badge">暂无</span>'}</div></div>`}
renderActorStats=function(actor){v1Profile(actor);const rel=actor.isPlayer?'自己':relationName(getRelation(state,'player',actor.id));return `<div class="npc-title"><strong>${escapeHtml(actor.name)}</strong><span class="badge ${actor.alive?'alive':'dead'}">${actor.alive?'存活':'死亡'}</span></div><div class="stat-grid"><div class="stat"><div class="label">境界</div><div class="value">${REALM_NAMES[actor.realm]}</div></div><div class="stat"><div class="label">年龄 / 寿元</div><div class="value">${actor.age}/${actor.lifespan}</div></div><div class="stat"><div class="label">气血</div><div class="value">${actor.hp}/${actor.maxHp}</div></div><div class="stat"><div class="label">灵气</div><div class="value">${actor.qi}/${actor.maxQi}</div></div><div class="stat"><div class="label">灵石</div><div class="value">${actor.wealth}</div></div><div class="stat"><div class="label">魅力</div><div class="value">${actor.charm}</div></div><div class="stat"><div class="label">悟性</div><div class="value">${actor.wisdom}</div></div><div class="stat"><div class="label">根骨</div><div class="value">${actor.bone}</div></div></div><div><span class="badge">性别：${actor.gender}</span><span class="badge">长相：${actor.face}</span><span class="badge">身材：${actor.body}</span><span class="badge">气质：${actor.aura}</span><span class="badge">灵根：${actor.root}</span><span class="badge">门派：${actor.sect}</span><span class="badge">位置：${getLocationName(actor.location)}</span><span class="badge">关系：${rel}</span></div>`}
renderNpcs=function(){el.npcList.innerHTML=state.actors.filter(a=>!a.isPlayer).map(a=>{v1Profile(a);return `<div class="npc-card"><div class="npc-title"><strong>${a.name}</strong><span class="badge ${a.alive?'alive':'dead'}">${REALM_NAMES[a.realm]}</span></div><div class="npc-meta">${a.gender}｜${a.face}｜${a.body}｜${a.sect}｜${getLocationName(a.location)}｜关系 ${getRelation(state,'player',a.id)}</div></div>`}).join('')}
renderRelations=function(){const list=state.actors.filter(a=>!a.isPlayer).map(a=>({a,score:getRelation(state,'player',a.id)})).sort((x,y)=>y.score-x.score);el.relationsGrid.innerHTML=list.map(({a,score})=>`<div class="relation"><div class="relation-title"><strong>${a.name}</strong><span class="badge">${relationName(score)}</span></div><div class="relation-meta">${a.gender}｜${a.face}｜${a.sect}｜${getLocationName(a.location)}｜关系 ${score}</div><div class="relation-bar"><div class="relation-fill" style="width:${clamp((score+100)/2,0,100)}%"></div></div></div>`).join('')}
const v1BaseRender=render;render=function(){v1PatchWorld();renderWorld();renderPlayer();renderTargets();renderMap();renderOrders();renderRelations();renderNpcs();renderLogs();renderScene();saveWorld()}
render();