console.log('V1X loaded');
function v1xEnsureNpc(id,name,temper,loc){if(findActor(id))return;const npc=createActor({id,name,isPlayer:false,temperament:temper,ambition:40,sect:'无门派',location:loc});npc.realm=0;npc.wealth=randInt(5,30);npc.items=randInt(0,2);state.actors.push(npc)}
function v1xBoot(){const p=findActor('player');if(!p)return;v1xEnsureNpc('npc_elder','村长','稳重','starter_village');v1xEnsureNpc('npc_herbalist','采药人','谨慎','starter_village');v1xEnsureNpc('npc_child','阿石','好奇','starter_village');state.actors.forEach(a=>{if(typeof v1Profile==='function')v1Profile(a)});if(!state.v1xNeutral){for(const a of state.actors){for(const b of state.actors){if(a.id!==b.id){setRelation(state,a.id,b.id,0);setHatred(state,a.id,b.id,0)}}}state.clues={};state.v1xNeutral=true;addLog(state,'你刚来到这个世界，和所有人都只是陌生人。','system');saveWorld()}}
function v1xAvatar(a,size='small'){const n=escapeHtml((a?.name||'?').slice(0,1));return `<div class="v1-avatar ${size}"><span>${n}</span></div>`}
function v1xTalk(id){const p=findActor('player');const n=findActor(id);if(!p||!n)return;changeRelation('player',id,randInt(2,5));changeRelation(id,'player',randInt(1,4));if(n.id==='npc_elder'){state.clues=state.clues||{};state.clues.qingyun=true;addLog(state,'村长说：若你真想修仙，可以沿北山古道去青云宗碰碰运气。','event')}else if(n.id==='npc_herbalist'){addLog(state,'采药人提醒你：进山前最好准备灵石和伤药，黑风林最近不太平。','event')}else if(n.id==='npc_child'){addLog(state,'阿石告诉你：坊市里常有散修讲述各宗门的消息。','event')}else{addLog(state,`${n.name}与你交谈了几句，对你多了一点印象。`,'event')}saveWorld();render()}
function v1xMoveTo(loc){const p=findActor('player');if(!p)return;p.location=loc;addLog(state,`你动身前往${getLocationName(loc)}。`,'event');saveWorld();render()}
renderScene=function(){v1xBoot();const p=findActor('player');const loc=getLocation(p.location);const near=state.actors.filter(a=>a.alive&&a.location===p.location&&a.id!==p.id).slice(0,8);const clues=state.clues||{};const exits=['starter_village','market','qingyun','black_forest'].filter(x=>x!==p.location);el.scenePanel.innerHTML=`<div class="v1-scene-wrap"><div class="v1-scene-text"><div class="scene-title">${getLocationName(p.location)}</div><p>${loc.desc} 你没有固定任务，也没有被系统安排好的路线。你能知道什么、遇到谁、和谁结怨或结交，都取决于你在这个世界里和谁说话，往哪里走。</p><div class="scene-block"><h3>身边人物</h3><div class="v1-nearby">${near.map(a=>`<button onclick="v1xTalk('${a.id}')">${a.name}｜${a.gender||''}｜${a.face||''}</button>`).join('')||'<span>附近暂无可交谈人物</span>'}</div></div><div class="scene-block"><h3>可前往地点</h3><div class="v1-nearby">${exits.map(id=>`<button onclick="v1xMoveTo('${id}')">${getLocationName(id)}</button>`).join('')}</div></div><div class="scene-block"><h3>已听到的线索</h3><p>${clues.qingyun?'村长提到北山古道尽头有青云宗，那里也许是凡人接触修仙的入口。':'你还没有得到可靠的修仙线索，可以先和村里人交谈。'}</p></div></div><div class="v1-scene-art"><b>${getLocationName(p.location)}</b></div></div>`}
renderRelations=function(){v1xBoot();const list=state.actors.filter(a=>!a.isPlayer).map(a=>({a,score:getRelation(state,'player',a.id)})).sort((x,y)=>Math.abs(y.score)-Math.abs(x.score));el.relationsGrid.innerHTML=list.map(({a,score})=>`<div class="v1-relation-row">${v1xAvatar(a)}<div><strong>${a.name}</strong><p>${a.gender||''}｜${a.face||''}｜${a.sect}｜${getLocationName(a.location)}</p><div class="relation-bar"><div class="relation-fill" style="width:${clamp((score+100)/2,0,100)}%"></div></div></div><b>${score===0?'未结识':relationName(score)}</b></div>`).join('')}
renderNpcs=function(){v1xBoot();el.npcList.innerHTML=state.actors.filter(a=>!a.isPlayer).map(a=>{const s=getRelation(state,'player',a.id);return `<div class="v1-npc-row">${v1xAvatar(a)}<div><strong>${a.name}</strong><p>${REALM_NAMES[a.realm]}｜${a.gender||''}｜${a.face||''}｜${a.sect}</p><p>${getLocationName(a.location)}｜${s===0?'未结识':'关系 '+s}</p></div><b>${a.location===findActor('player').location?'身边':'远方'}</b></div>`}).join('')}
renderLogs=function(){v1xBoot();const live=state.logs.slice(0,8);el.logList.innerHTML=live.map(l=>`<div class="log-item"><strong>${l.season} ${l.day}</strong> ${escapeHtml(l.text)}</div>`).join('')}
const v1xOldRender=render;render=function(){v1xBoot();renderWorld();renderPlayer();renderTargets();renderMap();renderOrders();renderRelations();renderNpcs();renderLogs();renderScene();saveWorld()}
v1xBoot();render();